cache: "/tmp/.bun-cache"

env:
  BUN_INSTALL_CACHE_DIR: "/tmp/.bun-cache"

x-plugins: &plugins
  - mise#v1.1.3: ~

steps:
  - label: ":oxc: check"
    key: check
    command: |
      mise ci
      mise check --format=junit > junit-lint.xml
    artifact_paths: junit-check.xml
    plugins: *plugins

  - label: ":typescript: typecheck"
    key: typecheck
    command: |
      mise ci
      mise typecheck
    plugins: *plugins

  - label: ":bun: test"
    key: test
    command: |
      mise ci
      mise test --reporter=junit --reporter-outfile=junit-test.xml
    artifact_paths: junit-test.xml
    plugins: *plugins

  - wait: ~
    continue_on_failure: true

  - label: ":junit:"
    key: test-summary
    plugins:
      - bugcrowd/test-summary#v1.11.0:
          inputs:
            - label: ":bun: test"
              artifact_path: junit-test.xml
              type: junit
            - label: ":oxc: check"
              artifact_path: junit-check.xml
              type: junit
          formatter:
            type: summary
          context: test-summary
