/**
 * Generated-file detection for the Diff view (diff-review.md §5): a built-in
 * default glob set — lockfiles, vendored/built output, minified assets, source
 * maps — that unions with the server's `.gitattributes linguist-generated`
 * hits (`Change.generated`). Generated files start from a viewed baseline.
 */

import { basename } from "./utils";

// Exact lockfile basenames that are machine-written and reviewed by their source.
const LOCKFILES = new Set([
  "Cargo.lock",
  "Gemfile.lock",
  "bun.lock",
  "bun.lockb",
  "composer.lock",
  "flake.lock",
  "go.sum",
  "package-lock.json",
  "pnpm-lock.yaml",
  "poetry.lock",
  "yarn.lock",
]);

// Path segments that mark vendored/built output anywhere in the tree.
const VENDORED_DIRS = new Set(["dist", "vendor", "node_modules"]);

/**
 * Whether a path is generated by the built-in default glob set: lockfiles,
 * `dist/`/`vendor/`/`node_modules/` output, minified assets, and source maps.
 */
export function isGeneratedPath(path: string): boolean {
  const name = basename(path);

  if (LOCKFILES.has(name)) {
    return true;
  }

  const segments = path.split("/");
  if (segments.some((segment) => VENDORED_DIRS.has(segment))) {
    return true;
  }

  return /\.min\.(?:js|css)$/.test(name) || name.endsWith(".map");
}
