#!/usr/bin/env bun
/**
 * Generate the embedded-asset manifest consumed by the compile entry
 * (`bin.ts`). Walks the Vite build under `dist/client/` and emits
 * `dist/embedded/manifest.ts`: one `import … with { type: "file" }` per built
 * file plus a `manifest` array mapping request path → embedded file.
 *
 * `bun build --compile bin.ts` embeds every imported file into the binary, so
 * the server serves the full UI with nothing on disk
 * (docs/spec/architecture.md §5). Running under `bun` (dev) the same imports
 * resolve to the on-disk `dist/client/` files, so one code path covers both.
 *
 *   bun run build:client && bun scripts/embed-assets.ts
 */

import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const repoRoot = path.join(import.meta.dir, "..");
const clientDir = path.join(repoRoot, "dist", "client");
const outDir = path.join(repoRoot, "dist", "embedded");
const outFile = path.join(outDir, "manifest.ts");

// All built files, as POSIX paths relative to dist/client (stable across OSes).
const files = readdirSync(clientDir, { recursive: true, withFileTypes: true })
  .filter((entry) => entry.isFile())
  .map((entry) =>
    path.relative(clientDir, path.join(entry.parentPath, entry.name)).replaceAll("\\", "/"),
  )
  .toSorted();

if (files.length === 0) {
  console.error(`no built client assets in ${clientDir} — run \`bun run build:client\` first`);
  process.exit(1);
}

// The manifest lives in dist/embedded; assets are one level over in dist/client.
const imports = files
  .map((file, i) => `import a${i} from "../client/${file}" with { type: "file" };`)
  .join("\n");
const entries = files.map((file, i) => `  { file: a${i}, path: "/${file}" },`).join("\n");

const source = `// GENERATED by scripts/embed-assets.ts — do not edit.
// ${files.length} built client asset(s) embedded via \`with { type: "file" }\`.
import type { ManifestEntry } from "../../src/client/assets.ts";

${imports}

export const manifest: readonly ManifestEntry[] = [
${entries}
];
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, source);
console.log(`embedded ${files.length} asset(s) → ${path.relative(repoRoot, outFile)}`);
