/**
 * Pure edge-case classification for the Diff tab's chrome (diff-review.md §5).
 * The renderer handles ordinary diff bodies; the surrounding cases — binary and
 * image files, renames, mode-only and submodule entries, oversized/minified
 * files, and generated/lockfile/vendored files — each need a different body
 * treatment and viewed/progress behavior. This module derives that per-file
 * classification from the same patch the renderer parses, so the chrome and the
 * body always agree. No DOM or React here.
 *
 * `FileDiffMetadata` carries no binary/image/generated flag, so the signals come
 * from two sources zipped by patch index: `processPatch` (type, modes, object
 * ids, hunks, line counts) and the raw per-file patch block (the authoritative
 * `Binary files … differ` marker the parser drops). Generated files fold in a
 * default glob set plus the server's `.gitattributes linguist-generated` hits.
 */

import type { FileDiffMetadata } from "@pierre/diffs";
import { processPatch } from "@pierre/diffs";

/** The orthogonal edge-case signals for one file, keyed by its item id. */
export interface FileClass {
  /** Binary content (git emitted `Binary files … differ`); images are a subset. */
  binary: boolean;
  /** A binary whose path is a raster image extension — rendered before/after. */
  image: boolean;
  /** A submodule (gitlink, mode 160000) — informational sha→sha row. */
  submodule: boolean;
  /** Only the file mode changed; no content and no blob. */
  modeOnly: boolean;
  /** A 100%-similarity rename — nothing to review. */
  renamePure: boolean;
  /** A rename that also edited content — normal diff under an `old → new` header. */
  renameModify: boolean;
  /** Past the size threshold, or carrying a minified megawide line. */
  large: boolean;
  /** Generated/lockfile/vendored — de-emphasized, collapsed, auto-viewed. */
  generated: boolean;
}

// Collapse the body past this many changed lines (diff-review.md §5: "e.g.
// >2k changed lines") — additions plus deletions, excluding context.
const LARGE_LINES = 2000;
// A single line this wide is minified/not human-readable — collapse regardless
// of line count ("a minified megabyte-wide line").
const MINIFIED_COLS = 5000;

// Raster image extensions rendered as before/after. SVG is intentionally absent:
// git treats it as text, so it never reaches the binary path and diffs normally.
const IMAGE_EXTENSIONS = new Set(["avif", "bmp", "gif", "ico", "jpeg", "jpg", "png", "webp"]);

// Exact lockfile basenames that are machine-written and reviewed by their source.
const LOCKFILES = new Set([
  "Cargo.lock",
  "Gemfile.lock",
  "bun.lock",
  "bun.lockb",
  "composer.lock",
  "flake.lock",
  "go.sum",
  "package-lock.json",
  "pnpm-lock.yaml",
  "poetry.lock",
  "yarn.lock",
]);

// Path segments that mark vendored/built output anywhere in the tree.
const VENDORED_DIRS = new Set(["dist", "vendor", "node_modules"]);

function basename(path: string): string {
  const slash = path.lastIndexOf("/");
  return slash === -1 ? path : path.slice(slash + 1);
}

function extension(path: string): string {
  const name = basename(path);
  const dot = name.lastIndexOf(".");
  return dot <= 0 ? "" : name.slice(dot + 1).toLowerCase();
}

/**
 * Whether a path is generated by the built-in default glob set (diff-review.md
 * §5): lockfiles, `dist/`/`vendor/`/`node_modules/` output, minified assets, and
 * source maps. The server's `.gitattributes linguist-generated` hits union with
 * this in `classifyFiles`.
 */
export function isGeneratedPath(path: string): boolean {
  const name = basename(path);
  if (LOCKFILES.has(name)) {
    return true;
  }
  const segments = path.split("/");
  if (segments.some((segment) => VENDORED_DIRS.has(segment))) {
    return true;
  }
  return /\.min\.(?:js|css)$/.test(name) || name.endsWith(".map");
}

// Split a raw unified patch into one block per file. Blocks begin at a
// column-0 `diff --git ` line; content lines are prefixed (`+`/`-`/space), so a
// file whose own content contains `diff --git` never triggers a false split.
const DIFF_HEADER = /^diff --git /m;

/**
 * Split a raw unified patch into its per-file blocks, in patch order — the same
 * order `processPatch` returns files, so the two zip by index.
 */
export function parsePatchBlocks(patch: string): string[] {
  if (patch.trim() === "") {
    return [];
  }
  const blocks: string[] = [];
  const parts = patch.split(DIFF_HEADER);
  for (const part of parts) {
    if (part === "") {
      continue;
    }
    blocks.push(`diff --git ${part}`);
  }
  return blocks;
}

const BINARY_MARKER = /^Binary files .* differ$/m;

function isImagePath(path: string): boolean {
  return IMAGE_EXTENSIONS.has(extension(path));
}

/** Changed-line count — additions plus deletions across the file's hunks. */
function changedLineCount(file: FileDiffMetadata): number {
  let count = 0;
  for (const hunk of file.hunks) {
    count += hunk.additionLines + hunk.deletionLines;
  }
  return count;
}

function maxLineLength(file: FileDiffMetadata): number {
  let max = 0;
  for (const line of file.additionLines) {
    max = Math.max(max, line.length);
  }
  for (const line of file.deletionLines) {
    max = Math.max(max, line.length);
  }
  return max;
}

/** Classify one file from its parsed metadata, raw block, and generated flag. */
function classifyFile(file: FileDiffMetadata, block: string, generated: boolean): FileClass {
  const submodule = file.mode === "160000" || file.prevMode === "160000";
  const binary = !submodule && BINARY_MARKER.test(block);
  const image = binary && isImagePath(file.name);
  const modeChanged =
    file.prevMode !== undefined && file.mode !== undefined && file.prevMode !== file.mode;
  const modeOnly = !binary && !submodule && file.hunks.length === 0 && modeChanged;
  const renamePure = file.type === "rename-pure";
  const renameModify = file.type === "rename-changed";
  const large =
    !binary &&
    !submodule &&
    (changedLineCount(file) > LARGE_LINES || maxLineLength(file) > MINIFIED_COLS);
  return {
    binary,
    generated,
    image,
    large,
    modeOnly,
    renameModify,
    renamePure,
    submodule,
  };
}

/**
 * Classify every file in a patch, keyed by CodeView item id (`name#index`).
 * `generatedPaths` is the server's `.gitattributes linguist-generated` set; it
 * unions with the default glob set so both sources mark a file generated.
 */
export function classifyFiles(
  patch: string,
  generatedPaths: readonly string[],
): Map<string, FileClass> {
  const generatedSet = new Set(generatedPaths);
  const blocks = parsePatchBlocks(patch);
  const classes = new Map<string, FileClass>();
  for (const [index, file] of processPatch(patch).files.entries()) {
    const generated = generatedSet.has(file.name) || isGeneratedPath(file.name);
    classes.set(`${file.name}#${index}`, classifyFile(file, blocks[index] ?? "", generated));
  }
  return classes;
}

/**
 * Whether a file marks itself viewed by default (diff-review.md §5): a pure
 * rename has nothing to review and a generated file is auto-marked-viewed. Both
 * stay counted in progress and can be un-viewed by the reviewer.
 */
export function autoViewed(file: FileClass): boolean {
  return file.renamePure === true || file.generated === true;
}

/**
 * Whether a file's diff body is replaced by an informational header row rather
 * than rendered (diff-review.md §5): binary and image files, mode-only changes,
 * and submodule entries. Large files keep a real (collapsible) body, so they are
 * excluded here.
 */
export function bodyReplaced(file: FileClass): boolean {
  return (
    file.binary === true || file.image === true || file.modeOnly === true || file.submodule === true
  );
}

// Powers-of-1024 units; binaries are byte-counted, so KB/MB read naturally.
const BYTE_UNITS = ["B", "KB", "MB", "GB"] as const;

/** Human-readable byte size for the binary size-delta chrome, e.g. `1.2 KB`. */
export function formatBytes(bytes: number): string {
  let value = bytes;
  let unit = 0;
  while (value >= 1024 && unit < BYTE_UNITS.length - 1) {
    value /= 1024;
    unit += 1;
  }
  const rounded = unit === 0 ? value : Math.round(value * 10) / 10;
  return `${rounded} ${BYTE_UNITS[unit]}`;
}
