/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as CodeRouteImport } from "./routes/code";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ProductRouteImport } from "./routes/product";

const ProductRoute = ProductRouteImport.update({
  id: "/product",
  path: "/product",
  getParentRoute: () => rootRouteImport,
} as any);
const CodeRoute = CodeRouteImport.update({
  id: "/code",
  path: "/code",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/code": typeof CodeRoute;
  "/product": typeof ProductRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/code": typeof CodeRoute;
  "/product": typeof ProductRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/code": typeof CodeRoute;
  "/product": typeof ProductRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/code" | "/product";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/code" | "/product";
  id: "__root__" | "/" | "/code" | "/product";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CodeRoute: typeof CodeRoute;
  ProductRoute: typeof ProductRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/product": {
      id: "/product";
      path: "/product";
      fullPath: "/product";
      preLoaderRoute: typeof ProductRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/code": {
      id: "/code";
      path: "/code";
      fullPath: "/code";
      preLoaderRoute: typeof CodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  ProductRoute: ProductRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
